name: Daily Instagram Scraper

on:
  schedule:
    - cron: "30 3 * * *"  # 每天台灣時間 11:30 AM 執行
  workflow_dispatch:  # 允許手動觸發

jobs:
  scrape_instagram:
    runs-on: ubuntu-latest

    steps:
      - name: 檢查 Repository
        uses: actions/checkout@v4

      - name: 設定 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: 安裝 Instaloader
        run: pip install instagrapi requests python-dotenv Pillow==8.1.1 --upgrade instagrapi

      - name: 執行 Instagram 爬蟲
        run: python ig_scraper.py
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
          TARGET_IG_USERNAME: ${{ secrets.TARGET_IG_USERNAME }}
          RENDER_API_URL: ${{ secrets.RENDER_API_URL }}